### ISSUE TITLE
ImportError: cannot import name 'NKSRNetwork' from 'nksr'

### ISSUE THREAD

**Issue by florentmaye** [nv-tlabs/NKSR#15]
Hi,

I'm trying to get the example working, but I got this error:

`python test.py configs/carla/train.yaml --url https://nksr.huangjh.tech/carla.pth  --include configs/carla/data_no_patch.yaml
Global seed set to 0
C:\Users\Zeus\AppData\Local\Programs\Python\Python311\Lib\site-packages\pytorch_lightning\trainer\connectors\accelerator_connector.py:467: LightningDeprecationWarning: Setting `Trainer(gpus=1)` is deprecated in v1.7 and will be removed in v2.0. Please use `Trainer(accelerator='gpu', devices=1)` instead.
  rank_zero_deprecation(
GPU available: True (cuda), used: True
TPU available: False, using: 0 TPU cores
IPU available: False, using: 0 IPUs
HPU available: False, using: 0 HPUs
Traceback (most recent call last):
  File "C:\Users\Zeus\Documents\project\MayeEnterprise\travaux\NVIDIA\NKSR-public\test.py", line 70, in <module>
    net_module = importlib.import_module("models." + args.model).Model
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Zeus\AppData\Local\Programs\Python\Python311\Lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1206, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1178, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1149, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\Users\Zeus\Documents\project\MayeEnterprise\travaux\NVIDIA\NKSR-public\models\nksr_net.py", line 15, in <module>
    from nksr import NKSRNetwork, SparseFeatureHierarchy
ImportError: cannot import name 'NKSRNetwork' from 'nksr' (C:\Users\Zeus\AppData\Local\Programs\Python\Python311\Lib\site-packages\nksr\__init__.py)`

Any idea of what could be the issue?

Thank you !

**Comment by heiwang1997** [comment]
Hi @florentmaye, unfortunately, we don't support Windows for now. Please use Linux and follow the instructions [here](https://github.com/nv-tlabs/NKSR#environment-setup) to set up your environment.

Thanks!!
