### ISSUE TITLE
RuntimeError: Not compiled with CUDA support

### ISSUE THREAD

**Issue by tqlhq** [nv-tlabs/NKSR#21]
When I run this code:recons_simple.py,it threats an error:

Traceback (most recent call last):
  File "/home/vector4d/NKSR/examples/recons_simple.py", line 26, in <module>
    field = reconstructor.reconstruct(input_xyz, input_normal, detail_level=1.0)
  File "/home/vector4d/anaconda3/envs/nksr2/lib/python3.10/site-packages/nksr/__init__.py", line 255, in reconstruct
    feat = self.network.encoder(xyz, feat, svh, 0)
  File "/home/vector4d/anaconda3/envs/nksr2/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/vector4d/anaconda3/envs/nksr2/lib/python3.10/site-packages/nksr/nn/encdec.py", line 105, in forward
    pooled = scatter_max(pts_feature, vid, dim=0, dim_size=grid.num_voxels)[0]
  File "/home/vector4d/anaconda3/envs/nksr2/lib/python3.10/site-packages/torch_scatter/scatter.py", line 72, in scatter_max
    return torch.ops.torch_scatter.scatter_max(src, index, dim, out, dim_size)
  File "/home/vector4d/anaconda3/envs/nksr2/lib/python3.10/site-packages/torch/_ops.py", line 502, in __call__
    return self._op(*args, **kwargs or {})
RuntimeError: Not compiled with CUDA support

My operating environment is python 3.10 torch2.0.0+cu118 (in conda)
How to solve this issue?Please help me !!!

**Comment by heiwang1997** [comment]
This seems to be a `torch_scatter`'s problem.
Did you create the conda environment using `environment.yml`? Or did you compile `torch_scatter` yourself?

**Comment by tqlhq** [comment]
Thank you very much for your answer. I have already solved this problem. Thank you again




---Original---
From: "Jiahui ***@***.***&gt;
Date: Mon, Jul 3, 2023 19:48 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [nv-tlabs/NKSR] RuntimeError: Not compiled with CUDA support(Issue #21)




 
This seems to be a torch_scatter's problem.
 Did you create the conda environment using environment.yml? Or did you compile torch_scatter yourself?

**Comment by heiwang1997** [comment]
OK it's great to hear that! Happy to help again.
