### ISSUE TITLE
Can not download model from URL `https://nksr.huangjh.tech/ks.pth`

### ISSUE THREAD

**Issue by Vincentqyw** [nv-tlabs/NKSR#37]
Thanks for your excellent work. I came across an error when running the following scripts:
``` python
field = reconstructor.reconstruct(input_xyz, input_normal, detail_level=1.0)
```
The error log is as follows:
``` bash
Downloading: "https://nksr.huangjh.tech/ks.pth" to /home/xxx/.cache/torch/hub/checkpoints/ks.pth
Traceback (most recent call last):
  File "/home/xxx/anaconda3/envs/imw/lib/python3.10/urllib/request.py", line 1348, in do_open
    h.request(req.get_method(), req.selector, req.data, headers,
  File "/home/xxx/anaconda3/envs/imw/lib/python3.10/http/client.py", line 1282, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/home/xxx/anaconda3/envs/imw/lib/python3.10/http/client.py", line 1328, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/home/xxx/anaconda3/envs/imw/lib/python3.10/http/client.py", line 1277, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/home/xxx/anaconda3/envs/imw/lib/python3.10/http/client.py", line 1037, in _send_output
    self.send(msg)
  File "/home/xxx/anaconda3/envs/imw/lib/python3.10/http/client.py", line 975, in send
    self.connect()
  File "/home/xxx/anaconda3/envs/imw/lib/python3.10/http/client.py", line 1447, in connect
    super().connect()
  File "/home/xxx/anaconda3/envs/imw/lib/python3.10/http/client.py", line 941, in connect
    self.sock = self._create_connection(
  File "/home/xxx/anaconda3/envs/imw/lib/python3.10/socket.py", line 845, in create_connection
    raise err
  File "/home/xxx/anaconda3/envs/imw/lib/python3.10/socket.py", line 833, in create_connection
    sock.connect(sa)
TimeoutError: [Errno 110] Connection timed out
```
I think the URL [`https://nksr.huangjh.tech`](https://nksr.huangjh.tech) is blocked by something, I don't know how to solve it. Could you please help me deal with this error? Thanks again.

**Comment by FrankBu0616** [comment]
running into a similar problem, 
```
Downloading: "https://nksr.huangjh.tech/ks.pth" to /home/frank/.cache/torch/hub/checkpoints/ks.pth
Traceback (most recent call last):
  File "/usr/lib/python3.10/urllib/request.py", line 1348, in do_open
    h.request(req.get_method(), req.selector, req.data, headers,
  File "/usr/lib/python3.10/http/client.py", line 1282, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/lib/python3.10/http/client.py", line 1328, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.10/http/client.py", line 1277, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.10/http/client.py", line 1037, in _send_output
    self.send(msg)
  File "/usr/lib/python3.10/http/client.py", line 975, in send
    self.connect()
  File "/usr/lib/python3.10/http/client.py", line 1447, in connect
    super().connect()
  File "/usr/lib/python3.10/http/client.py", line 941, in connect
    self.sock = self._create_connection(
  File "/usr/lib/python3.10/socket.py", line 845, in create_connection
    raise err
  File "/usr/lib/python3.10/socket.py", line 833, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused
```. 
Would appreciate any pointers.

**Comment by heiwang1997** [comment]
Oops sorry @Vincentqyw @FrankBu0616! I did some internal upgrades for my server this weekend and forgot to spin up the web service. Now it should be fixed. Let me know if things work :)

**Comment by Vincentqyw** [comment]
solved!

**Comment by FrankBu0616** [comment]
Yep same, thank you!
